import type { Metadata } from "next";

export const metadata: Metadata = {
  title: 'ratanov.pro👑',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="app">{children}</body>
    </html>
  )
}
